name: Build and deploy LaTeX PDF

on:
  push:
    paths:
      - 'wiki-guide/**.tex'
  workflow_dispatch:
jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: xu-cheng/latex-action@v2
        with:
          root_file: wiki-guide/main.tex
          latexmk_use_xelatex: true
          working_directory: wiki-guide
      - name: Copy PDF to docs
        run: |
          mkdir -p docs
          cp main.pdf wiki-guide.pdf
      - name: Commit PDF
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add wiki-guide.pdf
          git diff --cached --quiet || git commit -m "Update PDF"
          git push
