name: Build and deploy LaTeX PDF

on:
  push:
    paths:
      - 'wiki-guide/**.tex'
  workflow_dispatch:
jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Inkscape
        run: |
          wget https://media.inkscape.org/dl/resources/file/inkscape-1.3.2_2023-11-25_amd64.AppImage -O inkscape.AppImage
          chmod +x inkscape.AppImage
          sudo mv inkscape.AppImage /usr/local/bin/inkscape

      - uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          working_directory: wiki-guide

      - name: Copy PDF to docs
        run: |
          mkdir -p docs
          cp wiki-guide/main.pdf docs/wiki-guide.pdf
      - name: Commit PDF
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add docs/wiki-guide.pdf
          git diff --cached --quiet || git commit -m "Update PDF"
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

